### PR TITLE
Better popup for profile selection

### PR DESCRIPTION
**Pull request by TryHardDood**
The latest release will stay at the top and the others can be scrollable
image

### CODE REVIEW

**Comment by DarkLBP** [comment]
Seems that it is not working as intended

**Comment by TryHardDood** [comment]
It has something to do with the profiles order and the location. Otherthan that it's working 😄 
I'll fix it later when I have some time

**Comment by TryHardDood** [comment]
Can you test it? For me it works as it should.

**Comment by DarkLBP** [comment]
Still not working. I manged to fixed to keep the latest version on the top changing the addElement method to: 

`public void addElement(String id, Object aSet)
	{
		JMenuItem item = kernel.getProfiles().getProfile(id).getMenuItem();
		if (kernel.getProfiles().getSelectedProfile() != null && kernel.getProfiles().getSelectedProfile().equals(id)) {
			item.setFont(bold);
		}
		else {
			item.setFont(plain);
		}
		jPopupMenu.add(item).setActionCommand(String.valueOf(aSet));
		item.addActionListener(popupListener);
		if (kernel.getProfiles().getProfile(id).getType() == ProfileType.RELEASE) {
			jMenuItems.add(0, item); //Shifts all elements
			jPopupMenu.add(item, 0);
		}
		else {
			jMenuItems.add(item);
			jPopupMenu.add(item).setActionCommand(String.valueOf(aSet));
		}
	}`
However still exists the height problem. Creating profiles makes the popup appear higher.

**Comment by TryHardDood** [comment]
For some reason everytime I modify the JPopupMenu's contents ( adding or deleting an item ) it does not update the height.
After showing the menu it updates it self and it's working as intended.
Basically you have to click it twice..

Currently Idk how to fix this.

**Comment by DarkLBP** [comment]
I managed more or less to position properly the popup.

On the ProfilePopupMenu constructor change the MenuScroller line to this one:

MenuScroller.setScrollerFor(this.jPopupMenu, 4, 250, 1, 0);


Also change the showPopup method to this one:

public void showPopup(Component component) {
        Dimension d = jPopupMenu.getPreferredSize();
        d.width = 307;
        jPopupMenu.setPreferredSize(d);
        jPopupMenu.show(component, 0, -jPopupMenu.getPreferredSize().height + (jMenuItems.size() > 7 ? (jMenuItems.size() - 7) * 38 : 0) - 6);
    }


Let me know if it works

**Comment by TryHardDood** [comment]
After adding some profiles:
image
After removing:
image

**Comment by DarkLBP** [comment]
Mmm...
Try this showPopup method instead:

public void showPopup(Component component) {
        Dimension d = jPopupMenu.getPreferredSize();
        d.width = 307;
        d.height = 38 * jMenuItems.size();
        if (jMenuItems.size() >= 6) {
            d.height += 20;
        }
        jPopupMenu.setPreferredSize(d);
        jPopupMenu.show(component, 0, -jPopupMenu.getPreferredSize().height + (jMenuItems.size() > 7 ? (jMenuItems.size() - 7) * 38 : 0) - 6);
    }

**Comment by TryHardDood** [comment]
It's working

**Comment by DarkLBP** [comment]
Great. One less thing to be done :)

**Pull request merged**
