### PR TITLE
JavaFX

### PR DESCRIPTION
**Pull request by TryHardDood**
Only problem: You can't resize the window or it will break the aligments.

The News, Skins, Settings and Launcher settings buttons(tabs) are working just need to setup the contents.
image

Opened language selection dropdown. (ListView)
Opened profile selection dropup. (ListView)
image

### CODE REVIEW

**Comment by DarkLBP** [comment]
Great, thanks. I'm still trying to find out why the font misplaces the text a little to the top side.

**Comment by TryHardDood** [comment]
I believe thats a font bug. I'll try to fix it with a program but I'm not promising anything.

**Comment by DarkLBP** [comment]
But it is strange, with java swing there was no issue

**Comment by TryHardDood** [comment]
Maybe because it's a button not a label?

**Comment by TryHardDood** [comment]
I tried it with an another custom font, it's working properly.

**Comment by DarkLBP** [comment]
Which one did you use?

**Comment by TryHardDood** [comment]
This one: http://www.dafont.com/free-pixel.font

**Pull request merged**
